services:
  - type: web
    name: maple-markets
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEX_PUSH_KEY
        sync: false
